// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

#ifndef CXX_________LIBRARY_COMPONENTS_COMPONENT_HXX
#define CXX_________LIBRARY_COMPONENTS_COMPONENT_HXX

#ifndef XSD_CXX11
#define XSD_CXX11
#endif

#ifndef XSD_USE_CHAR
#define XSD_USE_CHAR
#endif

#ifndef XSD_CXX_TREE_USE_CHAR
#define XSD_CXX_TREE_USE_CHAR
#endif

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (LIBXSD_VERSION != 400002000000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/types.hxx>

#include <xsd/cxx/xml/error-handler.hxx>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

#include <xsd/cxx/tree/parsing.hxx>
#include <xsd/cxx/tree/parsing/byte.hxx>
#include <xsd/cxx/tree/parsing/unsigned-byte.hxx>
#include <xsd/cxx/tree/parsing/short.hxx>
#include <xsd/cxx/tree/parsing/unsigned-short.hxx>
#include <xsd/cxx/tree/parsing/int.hxx>
#include <xsd/cxx/tree/parsing/unsigned-int.hxx>
#include <xsd/cxx/tree/parsing/long.hxx>
#include <xsd/cxx/tree/parsing/unsigned-long.hxx>
#include <xsd/cxx/tree/parsing/boolean.hxx>
#include <xsd/cxx/tree/parsing/float.hxx>
#include <xsd/cxx/tree/parsing/double.hxx>
#include <xsd/cxx/tree/parsing/decimal.hxx>

namespace xml_schema
{
  // anyType and anySimpleType.
  //
  typedef ::xsd::cxx::tree::type type;
  typedef ::xsd::cxx::tree::simple_type< char, type > simple_type;
  typedef ::xsd::cxx::tree::type container;

  // 8-bit
  //
  typedef signed char byte;
  typedef unsigned char unsigned_byte;

  // 16-bit
  //
  typedef short short_;
  typedef unsigned short unsigned_short;

  // 32-bit
  //
  typedef int int_;
  typedef unsigned int unsigned_int;

  // 64-bit
  //
  typedef long long long_;
  typedef unsigned long long unsigned_long;

  // Supposed to be arbitrary-length integral types.
  //
  typedef long long integer;
  typedef long long non_positive_integer;
  typedef unsigned long long non_negative_integer;
  typedef unsigned long long positive_integer;
  typedef long long negative_integer;

  // Boolean.
  //
  typedef bool boolean;

  // Floating-point types.
  //
  typedef float float_;
  typedef double double_;
  typedef double decimal;

  // String types.
  //
  typedef ::xsd::cxx::tree::string< char, simple_type > string;
  typedef ::xsd::cxx::tree::normalized_string< char, string > normalized_string;
  typedef ::xsd::cxx::tree::token< char, normalized_string > token;
  typedef ::xsd::cxx::tree::name< char, token > name;
  typedef ::xsd::cxx::tree::nmtoken< char, token > nmtoken;
  typedef ::xsd::cxx::tree::nmtokens< char, simple_type, nmtoken > nmtokens;
  typedef ::xsd::cxx::tree::ncname< char, name > ncname;
  typedef ::xsd::cxx::tree::language< char, token > language;

  // ID/IDREF.
  //
  typedef ::xsd::cxx::tree::id< char, ncname > id;
  typedef ::xsd::cxx::tree::idref< char, ncname, type > idref;
  typedef ::xsd::cxx::tree::idrefs< char, simple_type, idref > idrefs;

  // URI.
  //
  typedef ::xsd::cxx::tree::uri< char, simple_type > uri;

  // Qualified name.
  //
  typedef ::xsd::cxx::tree::qname< char, simple_type, uri, ncname > qname;

  // Binary.
  //
  typedef ::xsd::cxx::tree::buffer< char > buffer;
  typedef ::xsd::cxx::tree::base64_binary< char, simple_type > base64_binary;
  typedef ::xsd::cxx::tree::hex_binary< char, simple_type > hex_binary;

  // Date/time.
  //
  typedef ::xsd::cxx::tree::time_zone time_zone;
  typedef ::xsd::cxx::tree::date< char, simple_type > date;
  typedef ::xsd::cxx::tree::date_time< char, simple_type > date_time;
  typedef ::xsd::cxx::tree::duration< char, simple_type > duration;
  typedef ::xsd::cxx::tree::gday< char, simple_type > gday;
  typedef ::xsd::cxx::tree::gmonth< char, simple_type > gmonth;
  typedef ::xsd::cxx::tree::gmonth_day< char, simple_type > gmonth_day;
  typedef ::xsd::cxx::tree::gyear< char, simple_type > gyear;
  typedef ::xsd::cxx::tree::gyear_month< char, simple_type > gyear_month;
  typedef ::xsd::cxx::tree::time< char, simple_type > time;

  // Entity.
  //
  typedef ::xsd::cxx::tree::entity< char, ncname > entity;
  typedef ::xsd::cxx::tree::entities< char, simple_type, entity > entities;

  typedef ::xsd::cxx::tree::content_order content_order;
  // Flags and properties.
  //
  typedef ::xsd::cxx::tree::flags flags;
  typedef ::xsd::cxx::tree::properties< char > properties;

  // Parsing/serialization diagnostics.
  //
  typedef ::xsd::cxx::tree::severity severity;
  typedef ::xsd::cxx::tree::error< char > error;
  typedef ::xsd::cxx::tree::diagnostics< char > diagnostics;

  // Exceptions.
  //
  typedef ::xsd::cxx::tree::exception< char > exception;
  typedef ::xsd::cxx::tree::bounds< char > bounds;
  typedef ::xsd::cxx::tree::duplicate_id< char > duplicate_id;
  typedef ::xsd::cxx::tree::parsing< char > parsing;
  typedef ::xsd::cxx::tree::expected_element< char > expected_element;
  typedef ::xsd::cxx::tree::unexpected_element< char > unexpected_element;
  typedef ::xsd::cxx::tree::expected_attribute< char > expected_attribute;
  typedef ::xsd::cxx::tree::unexpected_enumerator< char > unexpected_enumerator;
  typedef ::xsd::cxx::tree::expected_text_content< char > expected_text_content;
  typedef ::xsd::cxx::tree::no_prefix_mapping< char > no_prefix_mapping;

  // Error handler callback interface.
  //
  typedef ::xsd::cxx::xml::error_handler< char > error_handler;

  // DOM interaction.
  //
  namespace dom
  {
    // Automatic pointer for DOMDocument.
    //
    using ::xsd::cxx::xml::dom::unique_ptr;

#ifndef XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
#define XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
    // DOM user data key for back pointers to tree nodes.
    //
    const XMLCh* const tree_node_key = ::xsd::cxx::tree::user_data_keys::node;
#endif
  }
}

// Forward declarations.
//
namespace component
{
  namespace xml
  {
    class Component;
    class Models;
    class Netlists;
    class Symbols;
    class Parameters;
    class DefaultModel;
    class SpiceModel;
    class NgspiceNetlist;
    class Symbol;
    class Parameter;
    class Include;
    class PortSym;
    class Line;
  }
}


#include <memory>    // ::std::unique_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search
#include <utility>   // std::move

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

namespace component
{
  namespace xml
  {
    class Component: public ::xml_schema::type
    {
      public:
      // Description
      //
      typedef ::xml_schema::string Description_type;
      typedef ::xsd::cxx::tree::traits< Description_type, char > Description_traits;

      const Description_type&
      Description () const;

      Description_type&
      Description ();

      void
      Description (const Description_type& x);

      void
      Description (::std::unique_ptr< Description_type > p);

      // Models
      //
      typedef ::component::xml::Models Models_type;
      typedef ::xsd::cxx::tree::traits< Models_type, char > Models_traits;

      const Models_type&
      Models () const;

      Models_type&
      Models ();

      void
      Models (const Models_type& x);

      void
      Models (::std::unique_ptr< Models_type > p);

      // Netlists
      //
      typedef ::component::xml::Netlists Netlists_type;
      typedef ::xsd::cxx::tree::traits< Netlists_type, char > Netlists_traits;

      const Netlists_type&
      Netlists () const;

      Netlists_type&
      Netlists ();

      void
      Netlists (const Netlists_type& x);

      void
      Netlists (::std::unique_ptr< Netlists_type > p);

      // Symbols
      //
      typedef ::component::xml::Symbols Symbols_type;
      typedef ::xsd::cxx::tree::traits< Symbols_type, char > Symbols_traits;

      const Symbols_type&
      Symbols () const;

      Symbols_type&
      Symbols ();

      void
      Symbols (const Symbols_type& x);

      void
      Symbols (::std::unique_ptr< Symbols_type > p);

      // Parameters
      //
      typedef ::component::xml::Parameters Parameters_type;
      typedef ::xsd::cxx::tree::traits< Parameters_type, char > Parameters_traits;

      const Parameters_type&
      Parameters () const;

      Parameters_type&
      Parameters ();

      void
      Parameters (const Parameters_type& x);

      void
      Parameters (::std::unique_ptr< Parameters_type > p);

      // library
      //
      typedef ::xml_schema::string library_type;
      typedef ::xsd::cxx::tree::optional< library_type > library_optional;
      typedef ::xsd::cxx::tree::traits< library_type, char > library_traits;

      const library_optional&
      library () const;

      library_optional&
      library ();

      void
      library (const library_type& x);

      void
      library (const library_optional& x);

      void
      library (::std::unique_ptr< library_type > p);

      // name
      //
      typedef ::xml_schema::string name_type;
      typedef ::xsd::cxx::tree::optional< name_type > name_optional;
      typedef ::xsd::cxx::tree::traits< name_type, char > name_traits;

      const name_optional&
      name () const;

      name_optional&
      name ();

      void
      name (const name_type& x);

      void
      name (const name_optional& x);

      void
      name (::std::unique_ptr< name_type > p);

      // schematic_id
      //
      typedef ::xml_schema::string schematic_id_type;
      typedef ::xsd::cxx::tree::optional< schematic_id_type > schematic_id_optional;
      typedef ::xsd::cxx::tree::traits< schematic_id_type, char > schematic_id_traits;

      const schematic_id_optional&
      schematic_id () const;

      schematic_id_optional&
      schematic_id ();

      void
      schematic_id (const schematic_id_type& x);

      void
      schematic_id (const schematic_id_optional& x);

      void
      schematic_id (::std::unique_ptr< schematic_id_type > p);

      // Constructors.
      //
      Component (const Description_type&,
                 const Models_type&,
                 const Netlists_type&,
                 const Symbols_type&,
                 const Parameters_type&);

      Component (const Description_type&,
                 ::std::unique_ptr< Models_type >,
                 ::std::unique_ptr< Netlists_type >,
                 ::std::unique_ptr< Symbols_type >,
                 ::std::unique_ptr< Parameters_type >);

      Component (const ::xercesc::DOMElement& e,
                 ::xml_schema::flags f = 0,
                 ::xml_schema::container* c = 0);

      Component (const Component& x,
                 ::xml_schema::flags f = 0,
                 ::xml_schema::container* c = 0);

      virtual Component*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      Component&
      operator= (const Component& x);

      virtual 
      ~Component ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      ::xsd::cxx::tree::one< Description_type > Description_;
      ::xsd::cxx::tree::one< Models_type > Models_;
      ::xsd::cxx::tree::one< Netlists_type > Netlists_;
      ::xsd::cxx::tree::one< Symbols_type > Symbols_;
      ::xsd::cxx::tree::one< Parameters_type > Parameters_;
      library_optional library_;
      name_optional name_;
      schematic_id_optional schematic_id_;
    };

    class Models: public ::xml_schema::type
    {
      public:
      // DefaultModel
      //
      typedef ::component::xml::DefaultModel DefaultModel_type;
      typedef ::xsd::cxx::tree::traits< DefaultModel_type, char > DefaultModel_traits;

      const DefaultModel_type&
      DefaultModel () const;

      DefaultModel_type&
      DefaultModel ();

      void
      DefaultModel (const DefaultModel_type& x);

      void
      DefaultModel (::std::unique_ptr< DefaultModel_type > p);

      // SpiceModel
      //
      typedef ::component::xml::SpiceModel SpiceModel_type;
      typedef ::xsd::cxx::tree::traits< SpiceModel_type, char > SpiceModel_traits;

      const SpiceModel_type&
      SpiceModel () const;

      SpiceModel_type&
      SpiceModel ();

      void
      SpiceModel (const SpiceModel_type& x);

      void
      SpiceModel (::std::unique_ptr< SpiceModel_type > p);

      // Constructors.
      //
      Models (const DefaultModel_type&,
              const SpiceModel_type&);

      Models (::std::unique_ptr< DefaultModel_type >,
              ::std::unique_ptr< SpiceModel_type >);

      Models (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

      Models (const Models& x,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

      virtual Models*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      Models&
      operator= (const Models& x);

      virtual 
      ~Models ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      ::xsd::cxx::tree::one< DefaultModel_type > DefaultModel_;
      ::xsd::cxx::tree::one< SpiceModel_type > SpiceModel_;
    };

    class Netlists: public ::xml_schema::type
    {
      public:
      // NgspiceNetlist
      //
      typedef ::component::xml::NgspiceNetlist NgspiceNetlist_type;
      typedef ::xsd::cxx::tree::optional< NgspiceNetlist_type > NgspiceNetlist_optional;
      typedef ::xsd::cxx::tree::traits< NgspiceNetlist_type, char > NgspiceNetlist_traits;

      const NgspiceNetlist_optional&
      NgspiceNetlist () const;

      NgspiceNetlist_optional&
      NgspiceNetlist ();

      void
      NgspiceNetlist (const NgspiceNetlist_type& x);

      void
      NgspiceNetlist (const NgspiceNetlist_optional& x);

      void
      NgspiceNetlist (::std::unique_ptr< NgspiceNetlist_type > p);

      // Constructors.
      //
      Netlists ();

      Netlists (const ::xercesc::DOMElement& e,
                ::xml_schema::flags f = 0,
                ::xml_schema::container* c = 0);

      Netlists (const Netlists& x,
                ::xml_schema::flags f = 0,
                ::xml_schema::container* c = 0);

      virtual Netlists*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      Netlists&
      operator= (const Netlists& x);

      virtual 
      ~Netlists ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      NgspiceNetlist_optional NgspiceNetlist_;
    };

    class Symbols: public ::xml_schema::type
    {
      public:
      // Symbol
      //
      typedef ::component::xml::Symbol Symbol_type;
      typedef ::xsd::cxx::tree::traits< Symbol_type, char > Symbol_traits;

      const Symbol_type&
      Symbol () const;

      Symbol_type&
      Symbol ();

      void
      Symbol (const Symbol_type& x);

      void
      Symbol (::std::unique_ptr< Symbol_type > p);

      // Constructors.
      //
      Symbols (const Symbol_type&);

      Symbols (::std::unique_ptr< Symbol_type >);

      Symbols (const ::xercesc::DOMElement& e,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

      Symbols (const Symbols& x,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

      virtual Symbols*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      Symbols&
      operator= (const Symbols& x);

      virtual 
      ~Symbols ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      ::xsd::cxx::tree::one< Symbol_type > Symbol_;
    };

    class Parameters: public ::xml_schema::type
    {
      public:
      // Parameter
      //
      typedef ::component::xml::Parameter Parameter_type;
      typedef ::xsd::cxx::tree::sequence< Parameter_type > Parameter_sequence;
      typedef Parameter_sequence::iterator Parameter_iterator;
      typedef Parameter_sequence::const_iterator Parameter_const_iterator;
      typedef ::xsd::cxx::tree::traits< Parameter_type, char > Parameter_traits;

      const Parameter_sequence&
      Parameter () const;

      Parameter_sequence&
      Parameter ();

      void
      Parameter (const Parameter_sequence& s);

      // Constructors.
      //
      Parameters ();

      Parameters (const ::xercesc::DOMElement& e,
                  ::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0);

      Parameters (const Parameters& x,
                  ::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0);

      virtual Parameters*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      Parameters&
      operator= (const Parameters& x);

      virtual 
      ~Parameters ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      Parameter_sequence Parameter_;
    };

    class DefaultModel: public ::xml_schema::string
    {
      public:
      // value
      //
      typedef ::xml_schema::string value_type;
      typedef ::xsd::cxx::tree::optional< value_type > value_optional;
      typedef ::xsd::cxx::tree::traits< value_type, char > value_traits;

      const value_optional&
      value () const;

      value_optional&
      value ();

      void
      value (const value_type& x);

      void
      value (const value_optional& x);

      void
      value (::std::unique_ptr< value_type > p);

      // Constructors.
      //
      DefaultModel ();

      DefaultModel (const char*);

      DefaultModel (const ::std::string&);

      DefaultModel (const ::xml_schema::string&);

      DefaultModel (const ::xercesc::DOMElement& e,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

      DefaultModel (const DefaultModel& x,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

      virtual DefaultModel*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      DefaultModel&
      operator= (const DefaultModel& x);

      virtual 
      ~DefaultModel ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      value_optional value_;
    };

    class SpiceModel: public ::xml_schema::string
    {
      public:
      // value
      //
      typedef ::xml_schema::string value_type;
      typedef ::xsd::cxx::tree::optional< value_type > value_optional;
      typedef ::xsd::cxx::tree::traits< value_type, char > value_traits;

      const value_optional&
      value () const;

      value_optional&
      value ();

      void
      value (const value_type& x);

      void
      value (const value_optional& x);

      void
      value (::std::unique_ptr< value_type > p);

      // Constructors.
      //
      SpiceModel ();

      SpiceModel (const char*);

      SpiceModel (const ::std::string&);

      SpiceModel (const ::xml_schema::string&);

      SpiceModel (const ::xercesc::DOMElement& e,
                  ::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0);

      SpiceModel (const SpiceModel& x,
                  ::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0);

      virtual SpiceModel*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      SpiceModel&
      operator= (const SpiceModel& x);

      virtual 
      ~SpiceModel ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      value_optional value_;
    };

    class NgspiceNetlist: public ::xml_schema::type
    {
      public:
      // Include
      //
      typedef ::component::xml::Include Include_type;
      typedef ::xsd::cxx::tree::optional< Include_type > Include_optional;
      typedef ::xsd::cxx::tree::traits< Include_type, char > Include_traits;

      const Include_optional&
      Include () const;

      Include_optional&
      Include ();

      void
      Include (const Include_type& x);

      void
      Include (const Include_optional& x);

      void
      Include (::std::unique_ptr< Include_type > p);

      // value
      //
      typedef ::xml_schema::string value_type;
      typedef ::xsd::cxx::tree::optional< value_type > value_optional;
      typedef ::xsd::cxx::tree::traits< value_type, char > value_traits;

      const value_optional&
      value () const;

      value_optional&
      value ();

      void
      value (const value_type& x);

      void
      value (const value_optional& x);

      void
      value (::std::unique_ptr< value_type > p);

      // Constructors.
      //
      NgspiceNetlist ();

      NgspiceNetlist (const ::xercesc::DOMElement& e,
                      ::xml_schema::flags f = 0,
                      ::xml_schema::container* c = 0);

      NgspiceNetlist (const NgspiceNetlist& x,
                      ::xml_schema::flags f = 0,
                      ::xml_schema::container* c = 0);

      virtual NgspiceNetlist*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      NgspiceNetlist&
      operator= (const NgspiceNetlist& x);

      virtual 
      ~NgspiceNetlist ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      Include_optional Include_;
      value_optional value_;
    };

    class Symbol: public ::xml_schema::type
    {
      public:
      // PortSym
      //
      typedef ::component::xml::PortSym PortSym_type;
      typedef ::xsd::cxx::tree::sequence< PortSym_type > PortSym_sequence;
      typedef PortSym_sequence::iterator PortSym_iterator;
      typedef PortSym_sequence::const_iterator PortSym_const_iterator;
      typedef ::xsd::cxx::tree::traits< PortSym_type, char > PortSym_traits;

      const PortSym_sequence&
      PortSym () const;

      PortSym_sequence&
      PortSym ();

      void
      PortSym (const PortSym_sequence& s);

      // Line
      //
      typedef ::component::xml::Line Line_type;
      typedef ::xsd::cxx::tree::sequence< Line_type > Line_sequence;
      typedef Line_sequence::iterator Line_iterator;
      typedef Line_sequence::const_iterator Line_const_iterator;
      typedef ::xsd::cxx::tree::traits< Line_type, char > Line_traits;

      const Line_sequence&
      Line () const;

      Line_sequence&
      Line ();

      void
      Line (const Line_sequence& s);

      // id
      //
      typedef ::xml_schema::string id_type;
      typedef ::xsd::cxx::tree::optional< id_type > id_optional;
      typedef ::xsd::cxx::tree::traits< id_type, char > id_traits;

      const id_optional&
      id () const;

      id_optional&
      id ();

      void
      id (const id_type& x);

      void
      id (const id_optional& x);

      void
      id (::std::unique_ptr< id_type > p);

      // Constructors.
      //
      Symbol ();

      Symbol (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

      Symbol (const Symbol& x,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

      virtual Symbol*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      Symbol&
      operator= (const Symbol& x);

      virtual 
      ~Symbol ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      PortSym_sequence PortSym_;
      Line_sequence Line_;
      id_optional id_;
    };

    class Parameter: public ::xml_schema::type
    {
      public:
      // Description
      //
      typedef ::xml_schema::string Description_type;
      typedef ::xsd::cxx::tree::traits< Description_type, char > Description_traits;

      const Description_type&
      Description () const;

      Description_type&
      Description ();

      void
      Description (const Description_type& x);

      void
      Description (::std::unique_ptr< Description_type > p);

      // name
      //
      typedef ::xml_schema::string name_type;
      typedef ::xsd::cxx::tree::optional< name_type > name_optional;
      typedef ::xsd::cxx::tree::traits< name_type, char > name_traits;

      const name_optional&
      name () const;

      name_optional&
      name ();

      void
      name (const name_type& x);

      void
      name (const name_optional& x);

      void
      name (::std::unique_ptr< name_type > p);

      // unit
      //
      typedef ::xml_schema::string unit_type;
      typedef ::xsd::cxx::tree::optional< unit_type > unit_optional;
      typedef ::xsd::cxx::tree::traits< unit_type, char > unit_traits;

      const unit_optional&
      unit () const;

      unit_optional&
      unit ();

      void
      unit (const unit_type& x);

      void
      unit (const unit_optional& x);

      void
      unit (::std::unique_ptr< unit_type > p);

      // default_value
      //
      typedef ::xml_schema::string default_value_type;
      typedef ::xsd::cxx::tree::optional< default_value_type > default_value_optional;
      typedef ::xsd::cxx::tree::traits< default_value_type, char > default_value_traits;

      const default_value_optional&
      default_value () const;

      default_value_optional&
      default_value ();

      void
      default_value (const default_value_type& x);

      void
      default_value (const default_value_optional& x);

      void
      default_value (::std::unique_ptr< default_value_type > p);

      // show
      //
      typedef ::xml_schema::boolean show_type;
      typedef ::xsd::cxx::tree::optional< show_type > show_optional;
      typedef ::xsd::cxx::tree::traits< show_type, char > show_traits;

      const show_optional&
      show () const;

      show_optional&
      show ();

      void
      show (const show_type& x);

      void
      show (const show_optional& x);

      // Constructors.
      //
      Parameter (const Description_type&);

      Parameter (const ::xercesc::DOMElement& e,
                 ::xml_schema::flags f = 0,
                 ::xml_schema::container* c = 0);

      Parameter (const Parameter& x,
                 ::xml_schema::flags f = 0,
                 ::xml_schema::container* c = 0);

      virtual Parameter*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      Parameter&
      operator= (const Parameter& x);

      virtual 
      ~Parameter ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      ::xsd::cxx::tree::one< Description_type > Description_;
      name_optional name_;
      unit_optional unit_;
      default_value_optional default_value_;
      show_optional show_;
    };

    class Include: public ::xml_schema::string
    {
      public:
      // value
      //
      typedef ::xml_schema::string value_type;
      typedef ::xsd::cxx::tree::optional< value_type > value_optional;
      typedef ::xsd::cxx::tree::traits< value_type, char > value_traits;

      const value_optional&
      value () const;

      value_optional&
      value ();

      void
      value (const value_type& x);

      void
      value (const value_optional& x);

      void
      value (::std::unique_ptr< value_type > p);

      // Constructors.
      //
      Include ();

      Include (const char*);

      Include (const ::std::string&);

      Include (const ::xml_schema::string&);

      Include (const ::xercesc::DOMElement& e,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

      Include (const Include& x,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

      virtual Include*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      Include&
      operator= (const Include& x);

      virtual 
      ~Include ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      value_optional value_;
    };

    class PortSym: public ::xml_schema::string
    {
      public:
      // x
      //
      typedef ::xml_schema::int_ x_type;
      typedef ::xsd::cxx::tree::optional< x_type > x_optional;
      typedef ::xsd::cxx::tree::traits< x_type, char > x_traits;

      const x_optional&
      x () const;

      x_optional&
      x ();

      void
      x (const x_type& x);

      void
      x (const x_optional& x);

      // y
      //
      typedef ::xml_schema::int_ y_type;
      typedef ::xsd::cxx::tree::optional< y_type > y_optional;
      typedef ::xsd::cxx::tree::traits< y_type, char > y_traits;

      const y_optional&
      y () const;

      y_optional&
      y ();

      void
      y (const y_type& x);

      void
      y (const y_optional& x);

      // type
      //
      typedef ::xml_schema::byte type_type;
      typedef ::xsd::cxx::tree::optional< type_type > type_optional;
      typedef ::xsd::cxx::tree::traits< type_type, char > type_traits;

      const type_optional&
      type () const;

      type_optional&
      type ();

      void
      type (const type_type& x);

      void
      type (const type_optional& x);

      // angle
      //
      typedef ::xml_schema::short_ angle_type;
      typedef ::xsd::cxx::tree::optional< angle_type > angle_optional;
      typedef ::xsd::cxx::tree::traits< angle_type, char > angle_traits;

      const angle_optional&
      angle () const;

      angle_optional&
      angle ();

      void
      angle (const angle_type& x);

      void
      angle (const angle_optional& x);

      // Constructors.
      //
      PortSym ();

      PortSym (const char*);

      PortSym (const ::std::string&);

      PortSym (const ::xml_schema::string&);

      PortSym (const ::xercesc::DOMElement& e,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

      PortSym (const PortSym& x,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

      virtual PortSym*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      PortSym&
      operator= (const PortSym& x);

      virtual 
      ~PortSym ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      x_optional x_;
      y_optional y_;
      type_optional type_;
      angle_optional angle_;
    };

    class Line: public ::xml_schema::string
    {
      public:
      // x1
      //
      typedef ::xml_schema::int_ x1_type;
      typedef ::xsd::cxx::tree::optional< x1_type > x1_optional;
      typedef ::xsd::cxx::tree::traits< x1_type, char > x1_traits;

      const x1_optional&
      x1 () const;

      x1_optional&
      x1 ();

      void
      x1 (const x1_type& x);

      void
      x1 (const x1_optional& x);

      // y1
      //
      typedef ::xml_schema::int_ y1_type;
      typedef ::xsd::cxx::tree::optional< y1_type > y1_optional;
      typedef ::xsd::cxx::tree::traits< y1_type, char > y1_traits;

      const y1_optional&
      y1 () const;

      y1_optional&
      y1 ();

      void
      y1 (const y1_type& x);

      void
      y1 (const y1_optional& x);

      // x2
      //
      typedef ::xml_schema::int_ x2_type;
      typedef ::xsd::cxx::tree::optional< x2_type > x2_optional;
      typedef ::xsd::cxx::tree::traits< x2_type, char > x2_traits;

      const x2_optional&
      x2 () const;

      x2_optional&
      x2 ();

      void
      x2 (const x2_type& x);

      void
      x2 (const x2_optional& x);

      // y2
      //
      typedef ::xml_schema::int_ y2_type;
      typedef ::xsd::cxx::tree::optional< y2_type > y2_optional;
      typedef ::xsd::cxx::tree::traits< y2_type, char > y2_traits;

      const y2_optional&
      y2 () const;

      y2_optional&
      y2 ();

      void
      y2 (const y2_type& x);

      void
      y2 (const y2_optional& x);

      // color
      //
      typedef ::xml_schema::string color_type;
      typedef ::xsd::cxx::tree::optional< color_type > color_optional;
      typedef ::xsd::cxx::tree::traits< color_type, char > color_traits;

      const color_optional&
      color () const;

      color_optional&
      color ();

      void
      color (const color_type& x);

      void
      color (const color_optional& x);

      void
      color (::std::unique_ptr< color_type > p);

      // width
      //
      typedef ::xml_schema::int_ width_type;
      typedef ::xsd::cxx::tree::optional< width_type > width_optional;
      typedef ::xsd::cxx::tree::traits< width_type, char > width_traits;

      const width_optional&
      width () const;

      width_optional&
      width ();

      void
      width (const width_type& x);

      void
      width (const width_optional& x);

      // style
      //
      typedef ::xml_schema::byte style_type;
      typedef ::xsd::cxx::tree::optional< style_type > style_optional;
      typedef ::xsd::cxx::tree::traits< style_type, char > style_traits;

      const style_optional&
      style () const;

      style_optional&
      style ();

      void
      style (const style_type& x);

      void
      style (const style_optional& x);

      // x
      //
      typedef ::xml_schema::int_ x_type;
      typedef ::xsd::cxx::tree::optional< x_type > x_optional;
      typedef ::xsd::cxx::tree::traits< x_type, char > x_traits;

      const x_optional&
      x () const;

      x_optional&
      x ();

      void
      x (const x_type& x);

      void
      x (const x_optional& x);

      // y
      //
      typedef ::xml_schema::int_ y_type;
      typedef ::xsd::cxx::tree::optional< y_type > y_optional;
      typedef ::xsd::cxx::tree::traits< y_type, char > y_traits;

      const y_optional&
      y () const;

      y_optional&
      y ();

      void
      y (const y_type& x);

      void
      y (const y_optional& x);

      // type
      //
      typedef ::xml_schema::byte type_type;
      typedef ::xsd::cxx::tree::optional< type_type > type_optional;
      typedef ::xsd::cxx::tree::traits< type_type, char > type_traits;

      const type_optional&
      type () const;

      type_optional&
      type ();

      void
      type (const type_type& x);

      void
      type (const type_optional& x);

      // angle
      //
      typedef ::xml_schema::short_ angle_type;
      typedef ::xsd::cxx::tree::optional< angle_type > angle_optional;
      typedef ::xsd::cxx::tree::traits< angle_type, char > angle_traits;

      const angle_optional&
      angle () const;

      angle_optional&
      angle ();

      void
      angle (const angle_type& x);

      void
      angle (const angle_optional& x);

      // Constructors.
      //
      Line ();

      Line (const char*);

      Line (const ::std::string&);

      Line (const ::xml_schema::string&);

      Line (const ::xercesc::DOMElement& e,
            ::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0);

      Line (const Line& x,
            ::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0);

      virtual Line*
      _clone (::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0) const;

      Line&
      operator= (const Line& x);

      virtual 
      ~Line ();

      // Implementation.
      //
      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::flags);

      protected:
      x1_optional x1_;
      y1_optional y1_;
      x2_optional x2_;
      y2_optional y2_;
      color_optional color_;
      width_optional width_;
      style_optional style_;
      x_optional x_;
      y_optional y_;
      type_optional type_;
      angle_optional angle_;
    };
  }
}

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace component
{
  namespace xml
  {
    // Parse a URI or a local file.
    //

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (const ::std::string& uri,
                ::xml_schema::flags f = 0,
                const ::xml_schema::properties& p = ::xml_schema::properties ());

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (const ::std::string& uri,
                ::xml_schema::error_handler& eh,
                ::xml_schema::flags f = 0,
                const ::xml_schema::properties& p = ::xml_schema::properties ());

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (const ::std::string& uri,
                ::xercesc::DOMErrorHandler& eh,
                ::xml_schema::flags f = 0,
                const ::xml_schema::properties& p = ::xml_schema::properties ());

    // Parse std::istream.
    //

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::std::istream& is,
                ::xml_schema::flags f = 0,
                const ::xml_schema::properties& p = ::xml_schema::properties ());

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::std::istream& is,
                ::xml_schema::error_handler& eh,
                ::xml_schema::flags f = 0,
                const ::xml_schema::properties& p = ::xml_schema::properties ());

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::std::istream& is,
                ::xercesc::DOMErrorHandler& eh,
                ::xml_schema::flags f = 0,
                const ::xml_schema::properties& p = ::xml_schema::properties ());

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::std::istream& is,
                const ::std::string& id,
                ::xml_schema::flags f = 0,
                const ::xml_schema::properties& p = ::xml_schema::properties ());

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::std::istream& is,
                const ::std::string& id,
                ::xml_schema::error_handler& eh,
                ::xml_schema::flags f = 0,
                const ::xml_schema::properties& p = ::xml_schema::properties ());

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::std::istream& is,
                const ::std::string& id,
                ::xercesc::DOMErrorHandler& eh,
                ::xml_schema::flags f = 0,
                const ::xml_schema::properties& p = ::xml_schema::properties ());

    // Parse xercesc::InputSource.
    //

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::xercesc::InputSource& is,
                ::xml_schema::flags f = 0,
                const ::xml_schema::properties& p = ::xml_schema::properties ());

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::xercesc::InputSource& is,
                ::xml_schema::error_handler& eh,
                ::xml_schema::flags f = 0,
                const ::xml_schema::properties& p = ::xml_schema::properties ());

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::xercesc::InputSource& is,
                ::xercesc::DOMErrorHandler& eh,
                ::xml_schema::flags f = 0,
                const ::xml_schema::properties& p = ::xml_schema::properties ());

    // Parse xercesc::DOMDocument.
    //

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (const ::xercesc::DOMDocument& d,
                ::xml_schema::flags f = 0,
                const ::xml_schema::properties& p = ::xml_schema::properties ());

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
                ::xml_schema::flags f = 0,
                const ::xml_schema::properties& p = ::xml_schema::properties ());
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // CXX_________LIBRARY_COMPONENTS_COMPONENT_HXX
