// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "Component.hxx"

namespace component
{
  namespace xml
  {
    // Component
    //

    const Component::Description_type& Component::
    Description () const
    {
      return this->Description_.get ();
    }

    Component::Description_type& Component::
    Description ()
    {
      return this->Description_.get ();
    }

    void Component::
    Description (const Description_type& x)
    {
      this->Description_.set (x);
    }

    void Component::
    Description (::std::unique_ptr< Description_type > x)
    {
      this->Description_.set (std::move (x));
    }

    const Component::Models_type& Component::
    Models () const
    {
      return this->Models_.get ();
    }

    Component::Models_type& Component::
    Models ()
    {
      return this->Models_.get ();
    }

    void Component::
    Models (const Models_type& x)
    {
      this->Models_.set (x);
    }

    void Component::
    Models (::std::unique_ptr< Models_type > x)
    {
      this->Models_.set (std::move (x));
    }

    const Component::Netlists_type& Component::
    Netlists () const
    {
      return this->Netlists_.get ();
    }

    Component::Netlists_type& Component::
    Netlists ()
    {
      return this->Netlists_.get ();
    }

    void Component::
    Netlists (const Netlists_type& x)
    {
      this->Netlists_.set (x);
    }

    void Component::
    Netlists (::std::unique_ptr< Netlists_type > x)
    {
      this->Netlists_.set (std::move (x));
    }

    const Component::Symbols_type& Component::
    Symbols () const
    {
      return this->Symbols_.get ();
    }

    Component::Symbols_type& Component::
    Symbols ()
    {
      return this->Symbols_.get ();
    }

    void Component::
    Symbols (const Symbols_type& x)
    {
      this->Symbols_.set (x);
    }

    void Component::
    Symbols (::std::unique_ptr< Symbols_type > x)
    {
      this->Symbols_.set (std::move (x));
    }

    const Component::Parameters_type& Component::
    Parameters () const
    {
      return this->Parameters_.get ();
    }

    Component::Parameters_type& Component::
    Parameters ()
    {
      return this->Parameters_.get ();
    }

    void Component::
    Parameters (const Parameters_type& x)
    {
      this->Parameters_.set (x);
    }

    void Component::
    Parameters (::std::unique_ptr< Parameters_type > x)
    {
      this->Parameters_.set (std::move (x));
    }

    const Component::library_optional& Component::
    library () const
    {
      return this->library_;
    }

    Component::library_optional& Component::
    library ()
    {
      return this->library_;
    }

    void Component::
    library (const library_type& x)
    {
      this->library_.set (x);
    }

    void Component::
    library (const library_optional& x)
    {
      this->library_ = x;
    }

    void Component::
    library (::std::unique_ptr< library_type > x)
    {
      this->library_.set (std::move (x));
    }

    const Component::name_optional& Component::
    name () const
    {
      return this->name_;
    }

    Component::name_optional& Component::
    name ()
    {
      return this->name_;
    }

    void Component::
    name (const name_type& x)
    {
      this->name_.set (x);
    }

    void Component::
    name (const name_optional& x)
    {
      this->name_ = x;
    }

    void Component::
    name (::std::unique_ptr< name_type > x)
    {
      this->name_.set (std::move (x));
    }

    const Component::schematic_id_optional& Component::
    schematic_id () const
    {
      return this->schematic_id_;
    }

    Component::schematic_id_optional& Component::
    schematic_id ()
    {
      return this->schematic_id_;
    }

    void Component::
    schematic_id (const schematic_id_type& x)
    {
      this->schematic_id_.set (x);
    }

    void Component::
    schematic_id (const schematic_id_optional& x)
    {
      this->schematic_id_ = x;
    }

    void Component::
    schematic_id (::std::unique_ptr< schematic_id_type > x)
    {
      this->schematic_id_.set (std::move (x));
    }


    // Models
    //

    const Models::DefaultModel_type& Models::
    DefaultModel () const
    {
      return this->DefaultModel_.get ();
    }

    Models::DefaultModel_type& Models::
    DefaultModel ()
    {
      return this->DefaultModel_.get ();
    }

    void Models::
    DefaultModel (const DefaultModel_type& x)
    {
      this->DefaultModel_.set (x);
    }

    void Models::
    DefaultModel (::std::unique_ptr< DefaultModel_type > x)
    {
      this->DefaultModel_.set (std::move (x));
    }

    const Models::SpiceModel_type& Models::
    SpiceModel () const
    {
      return this->SpiceModel_.get ();
    }

    Models::SpiceModel_type& Models::
    SpiceModel ()
    {
      return this->SpiceModel_.get ();
    }

    void Models::
    SpiceModel (const SpiceModel_type& x)
    {
      this->SpiceModel_.set (x);
    }

    void Models::
    SpiceModel (::std::unique_ptr< SpiceModel_type > x)
    {
      this->SpiceModel_.set (std::move (x));
    }


    // Netlists
    //

    const Netlists::NgspiceNetlist_optional& Netlists::
    NgspiceNetlist () const
    {
      return this->NgspiceNetlist_;
    }

    Netlists::NgspiceNetlist_optional& Netlists::
    NgspiceNetlist ()
    {
      return this->NgspiceNetlist_;
    }

    void Netlists::
    NgspiceNetlist (const NgspiceNetlist_type& x)
    {
      this->NgspiceNetlist_.set (x);
    }

    void Netlists::
    NgspiceNetlist (const NgspiceNetlist_optional& x)
    {
      this->NgspiceNetlist_ = x;
    }

    void Netlists::
    NgspiceNetlist (::std::unique_ptr< NgspiceNetlist_type > x)
    {
      this->NgspiceNetlist_.set (std::move (x));
    }


    // Symbols
    //

    const Symbols::Symbol_type& Symbols::
    Symbol () const
    {
      return this->Symbol_.get ();
    }

    Symbols::Symbol_type& Symbols::
    Symbol ()
    {
      return this->Symbol_.get ();
    }

    void Symbols::
    Symbol (const Symbol_type& x)
    {
      this->Symbol_.set (x);
    }

    void Symbols::
    Symbol (::std::unique_ptr< Symbol_type > x)
    {
      this->Symbol_.set (std::move (x));
    }


    // Parameters
    //

    const Parameters::Parameter_sequence& Parameters::
    Parameter () const
    {
      return this->Parameter_;
    }

    Parameters::Parameter_sequence& Parameters::
    Parameter ()
    {
      return this->Parameter_;
    }

    void Parameters::
    Parameter (const Parameter_sequence& s)
    {
      this->Parameter_ = s;
    }


    // DefaultModel
    //

    const DefaultModel::value_optional& DefaultModel::
    value () const
    {
      return this->value_;
    }

    DefaultModel::value_optional& DefaultModel::
    value ()
    {
      return this->value_;
    }

    void DefaultModel::
    value (const value_type& x)
    {
      this->value_.set (x);
    }

    void DefaultModel::
    value (const value_optional& x)
    {
      this->value_ = x;
    }

    void DefaultModel::
    value (::std::unique_ptr< value_type > x)
    {
      this->value_.set (std::move (x));
    }


    // SpiceModel
    //

    const SpiceModel::value_optional& SpiceModel::
    value () const
    {
      return this->value_;
    }

    SpiceModel::value_optional& SpiceModel::
    value ()
    {
      return this->value_;
    }

    void SpiceModel::
    value (const value_type& x)
    {
      this->value_.set (x);
    }

    void SpiceModel::
    value (const value_optional& x)
    {
      this->value_ = x;
    }

    void SpiceModel::
    value (::std::unique_ptr< value_type > x)
    {
      this->value_.set (std::move (x));
    }


    // NgspiceNetlist
    //

    const NgspiceNetlist::Include_optional& NgspiceNetlist::
    Include () const
    {
      return this->Include_;
    }

    NgspiceNetlist::Include_optional& NgspiceNetlist::
    Include ()
    {
      return this->Include_;
    }

    void NgspiceNetlist::
    Include (const Include_type& x)
    {
      this->Include_.set (x);
    }

    void NgspiceNetlist::
    Include (const Include_optional& x)
    {
      this->Include_ = x;
    }

    void NgspiceNetlist::
    Include (::std::unique_ptr< Include_type > x)
    {
      this->Include_.set (std::move (x));
    }

    const NgspiceNetlist::value_optional& NgspiceNetlist::
    value () const
    {
      return this->value_;
    }

    NgspiceNetlist::value_optional& NgspiceNetlist::
    value ()
    {
      return this->value_;
    }

    void NgspiceNetlist::
    value (const value_type& x)
    {
      this->value_.set (x);
    }

    void NgspiceNetlist::
    value (const value_optional& x)
    {
      this->value_ = x;
    }

    void NgspiceNetlist::
    value (::std::unique_ptr< value_type > x)
    {
      this->value_.set (std::move (x));
    }


    // Symbol
    //

    const Symbol::PortSym_sequence& Symbol::
    PortSym () const
    {
      return this->PortSym_;
    }

    Symbol::PortSym_sequence& Symbol::
    PortSym ()
    {
      return this->PortSym_;
    }

    void Symbol::
    PortSym (const PortSym_sequence& s)
    {
      this->PortSym_ = s;
    }

    const Symbol::Line_sequence& Symbol::
    Line () const
    {
      return this->Line_;
    }

    Symbol::Line_sequence& Symbol::
    Line ()
    {
      return this->Line_;
    }

    void Symbol::
    Line (const Line_sequence& s)
    {
      this->Line_ = s;
    }

    const Symbol::id_optional& Symbol::
    id () const
    {
      return this->id_;
    }

    Symbol::id_optional& Symbol::
    id ()
    {
      return this->id_;
    }

    void Symbol::
    id (const id_type& x)
    {
      this->id_.set (x);
    }

    void Symbol::
    id (const id_optional& x)
    {
      this->id_ = x;
    }

    void Symbol::
    id (::std::unique_ptr< id_type > x)
    {
      this->id_.set (std::move (x));
    }


    // Parameter
    //

    const Parameter::Description_type& Parameter::
    Description () const
    {
      return this->Description_.get ();
    }

    Parameter::Description_type& Parameter::
    Description ()
    {
      return this->Description_.get ();
    }

    void Parameter::
    Description (const Description_type& x)
    {
      this->Description_.set (x);
    }

    void Parameter::
    Description (::std::unique_ptr< Description_type > x)
    {
      this->Description_.set (std::move (x));
    }

    const Parameter::name_optional& Parameter::
    name () const
    {
      return this->name_;
    }

    Parameter::name_optional& Parameter::
    name ()
    {
      return this->name_;
    }

    void Parameter::
    name (const name_type& x)
    {
      this->name_.set (x);
    }

    void Parameter::
    name (const name_optional& x)
    {
      this->name_ = x;
    }

    void Parameter::
    name (::std::unique_ptr< name_type > x)
    {
      this->name_.set (std::move (x));
    }

    const Parameter::unit_optional& Parameter::
    unit () const
    {
      return this->unit_;
    }

    Parameter::unit_optional& Parameter::
    unit ()
    {
      return this->unit_;
    }

    void Parameter::
    unit (const unit_type& x)
    {
      this->unit_.set (x);
    }

    void Parameter::
    unit (const unit_optional& x)
    {
      this->unit_ = x;
    }

    void Parameter::
    unit (::std::unique_ptr< unit_type > x)
    {
      this->unit_.set (std::move (x));
    }

    const Parameter::default_value_optional& Parameter::
    default_value () const
    {
      return this->default_value_;
    }

    Parameter::default_value_optional& Parameter::
    default_value ()
    {
      return this->default_value_;
    }

    void Parameter::
    default_value (const default_value_type& x)
    {
      this->default_value_.set (x);
    }

    void Parameter::
    default_value (const default_value_optional& x)
    {
      this->default_value_ = x;
    }

    void Parameter::
    default_value (::std::unique_ptr< default_value_type > x)
    {
      this->default_value_.set (std::move (x));
    }

    const Parameter::show_optional& Parameter::
    show () const
    {
      return this->show_;
    }

    Parameter::show_optional& Parameter::
    show ()
    {
      return this->show_;
    }

    void Parameter::
    show (const show_type& x)
    {
      this->show_.set (x);
    }

    void Parameter::
    show (const show_optional& x)
    {
      this->show_ = x;
    }


    // Include
    //

    const Include::value_optional& Include::
    value () const
    {
      return this->value_;
    }

    Include::value_optional& Include::
    value ()
    {
      return this->value_;
    }

    void Include::
    value (const value_type& x)
    {
      this->value_.set (x);
    }

    void Include::
    value (const value_optional& x)
    {
      this->value_ = x;
    }

    void Include::
    value (::std::unique_ptr< value_type > x)
    {
      this->value_.set (std::move (x));
    }


    // PortSym
    //

    const PortSym::x_optional& PortSym::
    x () const
    {
      return this->x_;
    }

    PortSym::x_optional& PortSym::
    x ()
    {
      return this->x_;
    }

    void PortSym::
    x (const x_type& x)
    {
      this->x_.set (x);
    }

    void PortSym::
    x (const x_optional& x)
    {
      this->x_ = x;
    }

    const PortSym::y_optional& PortSym::
    y () const
    {
      return this->y_;
    }

    PortSym::y_optional& PortSym::
    y ()
    {
      return this->y_;
    }

    void PortSym::
    y (const y_type& x)
    {
      this->y_.set (x);
    }

    void PortSym::
    y (const y_optional& x)
    {
      this->y_ = x;
    }

    const PortSym::type_optional& PortSym::
    type () const
    {
      return this->type_;
    }

    PortSym::type_optional& PortSym::
    type ()
    {
      return this->type_;
    }

    void PortSym::
    type (const type_type& x)
    {
      this->type_.set (x);
    }

    void PortSym::
    type (const type_optional& x)
    {
      this->type_ = x;
    }

    const PortSym::angle_optional& PortSym::
    angle () const
    {
      return this->angle_;
    }

    PortSym::angle_optional& PortSym::
    angle ()
    {
      return this->angle_;
    }

    void PortSym::
    angle (const angle_type& x)
    {
      this->angle_.set (x);
    }

    void PortSym::
    angle (const angle_optional& x)
    {
      this->angle_ = x;
    }


    // Line
    //

    const Line::x1_optional& Line::
    x1 () const
    {
      return this->x1_;
    }

    Line::x1_optional& Line::
    x1 ()
    {
      return this->x1_;
    }

    void Line::
    x1 (const x1_type& x)
    {
      this->x1_.set (x);
    }

    void Line::
    x1 (const x1_optional& x)
    {
      this->x1_ = x;
    }

    const Line::y1_optional& Line::
    y1 () const
    {
      return this->y1_;
    }

    Line::y1_optional& Line::
    y1 ()
    {
      return this->y1_;
    }

    void Line::
    y1 (const y1_type& x)
    {
      this->y1_.set (x);
    }

    void Line::
    y1 (const y1_optional& x)
    {
      this->y1_ = x;
    }

    const Line::x2_optional& Line::
    x2 () const
    {
      return this->x2_;
    }

    Line::x2_optional& Line::
    x2 ()
    {
      return this->x2_;
    }

    void Line::
    x2 (const x2_type& x)
    {
      this->x2_.set (x);
    }

    void Line::
    x2 (const x2_optional& x)
    {
      this->x2_ = x;
    }

    const Line::y2_optional& Line::
    y2 () const
    {
      return this->y2_;
    }

    Line::y2_optional& Line::
    y2 ()
    {
      return this->y2_;
    }

    void Line::
    y2 (const y2_type& x)
    {
      this->y2_.set (x);
    }

    void Line::
    y2 (const y2_optional& x)
    {
      this->y2_ = x;
    }

    const Line::color_optional& Line::
    color () const
    {
      return this->color_;
    }

    Line::color_optional& Line::
    color ()
    {
      return this->color_;
    }

    void Line::
    color (const color_type& x)
    {
      this->color_.set (x);
    }

    void Line::
    color (const color_optional& x)
    {
      this->color_ = x;
    }

    void Line::
    color (::std::unique_ptr< color_type > x)
    {
      this->color_.set (std::move (x));
    }

    const Line::width_optional& Line::
    width () const
    {
      return this->width_;
    }

    Line::width_optional& Line::
    width ()
    {
      return this->width_;
    }

    void Line::
    width (const width_type& x)
    {
      this->width_.set (x);
    }

    void Line::
    width (const width_optional& x)
    {
      this->width_ = x;
    }

    const Line::style_optional& Line::
    style () const
    {
      return this->style_;
    }

    Line::style_optional& Line::
    style ()
    {
      return this->style_;
    }

    void Line::
    style (const style_type& x)
    {
      this->style_.set (x);
    }

    void Line::
    style (const style_optional& x)
    {
      this->style_ = x;
    }

    const Line::x_optional& Line::
    x () const
    {
      return this->x_;
    }

    Line::x_optional& Line::
    x ()
    {
      return this->x_;
    }

    void Line::
    x (const x_type& x)
    {
      this->x_.set (x);
    }

    void Line::
    x (const x_optional& x)
    {
      this->x_ = x;
    }

    const Line::y_optional& Line::
    y () const
    {
      return this->y_;
    }

    Line::y_optional& Line::
    y ()
    {
      return this->y_;
    }

    void Line::
    y (const y_type& x)
    {
      this->y_.set (x);
    }

    void Line::
    y (const y_optional& x)
    {
      this->y_ = x;
    }

    const Line::type_optional& Line::
    type () const
    {
      return this->type_;
    }

    Line::type_optional& Line::
    type ()
    {
      return this->type_;
    }

    void Line::
    type (const type_type& x)
    {
      this->type_.set (x);
    }

    void Line::
    type (const type_optional& x)
    {
      this->type_ = x;
    }

    const Line::angle_optional& Line::
    angle () const
    {
      return this->angle_;
    }

    Line::angle_optional& Line::
    angle ()
    {
      return this->angle_;
    }

    void Line::
    angle (const angle_type& x)
    {
      this->angle_.set (x);
    }

    void Line::
    angle (const angle_optional& x)
    {
      this->angle_ = x;
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace component
{
  namespace xml
  {
    // Component
    //

    Component::
    Component (const Description_type& Description,
               const Models_type& Models,
               const Netlists_type& Netlists,
               const Symbols_type& Symbols,
               const Parameters_type& Parameters)
    : ::xml_schema::type (),
      Description_ (Description, this),
      Models_ (Models, this),
      Netlists_ (Netlists, this),
      Symbols_ (Symbols, this),
      Parameters_ (Parameters, this),
      library_ (this),
      name_ (this),
      schematic_id_ (this)
    {
    }

    Component::
    Component (const Description_type& Description,
               ::std::unique_ptr< Models_type > Models,
               ::std::unique_ptr< Netlists_type > Netlists,
               ::std::unique_ptr< Symbols_type > Symbols,
               ::std::unique_ptr< Parameters_type > Parameters)
    : ::xml_schema::type (),
      Description_ (Description, this),
      Models_ (std::move (Models), this),
      Netlists_ (std::move (Netlists), this),
      Symbols_ (std::move (Symbols), this),
      Parameters_ (std::move (Parameters), this),
      library_ (this),
      name_ (this),
      schematic_id_ (this)
    {
    }

    Component::
    Component (const Component& x,
               ::xml_schema::flags f,
               ::xml_schema::container* c)
    : ::xml_schema::type (x, f, c),
      Description_ (x.Description_, f, this),
      Models_ (x.Models_, f, this),
      Netlists_ (x.Netlists_, f, this),
      Symbols_ (x.Symbols_, f, this),
      Parameters_ (x.Parameters_, f, this),
      library_ (x.library_, f, this),
      name_ (x.name_, f, this),
      schematic_id_ (x.schematic_id_, f, this)
    {
    }

    Component::
    Component (const ::xercesc::DOMElement& e,
               ::xml_schema::flags f,
               ::xml_schema::container* c)
    : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
      Description_ (this),
      Models_ (this),
      Netlists_ (this),
      Symbols_ (this),
      Parameters_ (this),
      library_ (this),
      name_ (this),
      schematic_id_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
        this->parse (p, f);
      }
    }

    void Component::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // Description
        //
        if (n.name () == "Description" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< Description_type > r (
            Description_traits::create (i, f, this));

          if (!Description_.present ())
          {
            this->Description_.set (::std::move (r));
            continue;
          }
        }

        // Models
        //
        if (n.name () == "Models" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< Models_type > r (
            Models_traits::create (i, f, this));

          if (!Models_.present ())
          {
            this->Models_.set (::std::move (r));
            continue;
          }
        }

        // Netlists
        //
        if (n.name () == "Netlists" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< Netlists_type > r (
            Netlists_traits::create (i, f, this));

          if (!Netlists_.present ())
          {
            this->Netlists_.set (::std::move (r));
            continue;
          }
        }

        // Symbols
        //
        if (n.name () == "Symbols" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< Symbols_type > r (
            Symbols_traits::create (i, f, this));

          if (!Symbols_.present ())
          {
            this->Symbols_.set (::std::move (r));
            continue;
          }
        }

        // Parameters
        //
        if (n.name () == "Parameters" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< Parameters_type > r (
            Parameters_traits::create (i, f, this));

          if (!Parameters_.present ())
          {
            this->Parameters_.set (::std::move (r));
            continue;
          }
        }

        break;
      }

      if (!Description_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "Description",
          "");
      }

      if (!Models_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "Models",
          "");
      }

      if (!Netlists_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "Netlists",
          "");
      }

      if (!Symbols_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "Symbols",
          "");
      }

      if (!Parameters_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "Parameters",
          "");
      }

      while (p.more_attributes ())
      {
        const ::xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        if (n.name () == "library" && n.namespace_ ().empty ())
        {
          this->library_.set (library_traits::create (i, f, this));
          continue;
        }

        if (n.name () == "name" && n.namespace_ ().empty ())
        {
          this->name_.set (name_traits::create (i, f, this));
          continue;
        }

        if (n.name () == "schematic_id" && n.namespace_ ().empty ())
        {
          this->schematic_id_.set (schematic_id_traits::create (i, f, this));
          continue;
        }
      }
    }

    Component* Component::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class Component (*this, f, c);
    }

    Component& Component::
    operator= (const Component& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::type& > (*this) = x;
        this->Description_ = x.Description_;
        this->Models_ = x.Models_;
        this->Netlists_ = x.Netlists_;
        this->Symbols_ = x.Symbols_;
        this->Parameters_ = x.Parameters_;
        this->library_ = x.library_;
        this->name_ = x.name_;
        this->schematic_id_ = x.schematic_id_;
      }

      return *this;
    }

    Component::
    ~Component ()
    {
    }

    // Models
    //

    Models::
    Models (const DefaultModel_type& DefaultModel,
            const SpiceModel_type& SpiceModel)
    : ::xml_schema::type (),
      DefaultModel_ (DefaultModel, this),
      SpiceModel_ (SpiceModel, this)
    {
    }

    Models::
    Models (::std::unique_ptr< DefaultModel_type > DefaultModel,
            ::std::unique_ptr< SpiceModel_type > SpiceModel)
    : ::xml_schema::type (),
      DefaultModel_ (std::move (DefaultModel), this),
      SpiceModel_ (std::move (SpiceModel), this)
    {
    }

    Models::
    Models (const Models& x,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
    : ::xml_schema::type (x, f, c),
      DefaultModel_ (x.DefaultModel_, f, this),
      SpiceModel_ (x.SpiceModel_, f, this)
    {
    }

    Models::
    Models (const ::xercesc::DOMElement& e,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
    : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
      DefaultModel_ (this),
      SpiceModel_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
        this->parse (p, f);
      }
    }

    void Models::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // DefaultModel
        //
        if (n.name () == "DefaultModel" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< DefaultModel_type > r (
            DefaultModel_traits::create (i, f, this));

          if (!DefaultModel_.present ())
          {
            this->DefaultModel_.set (::std::move (r));
            continue;
          }
        }

        // SpiceModel
        //
        if (n.name () == "SpiceModel" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< SpiceModel_type > r (
            SpiceModel_traits::create (i, f, this));

          if (!SpiceModel_.present ())
          {
            this->SpiceModel_.set (::std::move (r));
            continue;
          }
        }

        break;
      }

      if (!DefaultModel_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "DefaultModel",
          "");
      }

      if (!SpiceModel_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "SpiceModel",
          "");
      }
    }

    Models* Models::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class Models (*this, f, c);
    }

    Models& Models::
    operator= (const Models& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::type& > (*this) = x;
        this->DefaultModel_ = x.DefaultModel_;
        this->SpiceModel_ = x.SpiceModel_;
      }

      return *this;
    }

    Models::
    ~Models ()
    {
    }

    // Netlists
    //

    Netlists::
    Netlists ()
    : ::xml_schema::type (),
      NgspiceNetlist_ (this)
    {
    }

    Netlists::
    Netlists (const Netlists& x,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
    : ::xml_schema::type (x, f, c),
      NgspiceNetlist_ (x.NgspiceNetlist_, f, this)
    {
    }

    Netlists::
    Netlists (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f,
              ::xml_schema::container* c)
    : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
      NgspiceNetlist_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
        this->parse (p, f);
      }
    }

    void Netlists::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // NgspiceNetlist
        //
        if (n.name () == "NgspiceNetlist" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< NgspiceNetlist_type > r (
            NgspiceNetlist_traits::create (i, f, this));

          if (!this->NgspiceNetlist_)
          {
            this->NgspiceNetlist_.set (::std::move (r));
            continue;
          }
        }

        break;
      }
    }

    Netlists* Netlists::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class Netlists (*this, f, c);
    }

    Netlists& Netlists::
    operator= (const Netlists& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::type& > (*this) = x;
        this->NgspiceNetlist_ = x.NgspiceNetlist_;
      }

      return *this;
    }

    Netlists::
    ~Netlists ()
    {
    }

    // Symbols
    //

    Symbols::
    Symbols (const Symbol_type& Symbol)
    : ::xml_schema::type (),
      Symbol_ (Symbol, this)
    {
    }

    Symbols::
    Symbols (::std::unique_ptr< Symbol_type > Symbol)
    : ::xml_schema::type (),
      Symbol_ (std::move (Symbol), this)
    {
    }

    Symbols::
    Symbols (const Symbols& x,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
    : ::xml_schema::type (x, f, c),
      Symbol_ (x.Symbol_, f, this)
    {
    }

    Symbols::
    Symbols (const ::xercesc::DOMElement& e,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
    : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
      Symbol_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
        this->parse (p, f);
      }
    }

    void Symbols::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // Symbol
        //
        if (n.name () == "Symbol" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< Symbol_type > r (
            Symbol_traits::create (i, f, this));

          if (!Symbol_.present ())
          {
            this->Symbol_.set (::std::move (r));
            continue;
          }
        }

        break;
      }

      if (!Symbol_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "Symbol",
          "");
      }
    }

    Symbols* Symbols::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class Symbols (*this, f, c);
    }

    Symbols& Symbols::
    operator= (const Symbols& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::type& > (*this) = x;
        this->Symbol_ = x.Symbol_;
      }

      return *this;
    }

    Symbols::
    ~Symbols ()
    {
    }

    // Parameters
    //

    Parameters::
    Parameters ()
    : ::xml_schema::type (),
      Parameter_ (this)
    {
    }

    Parameters::
    Parameters (const Parameters& x,
                ::xml_schema::flags f,
                ::xml_schema::container* c)
    : ::xml_schema::type (x, f, c),
      Parameter_ (x.Parameter_, f, this)
    {
    }

    Parameters::
    Parameters (const ::xercesc::DOMElement& e,
                ::xml_schema::flags f,
                ::xml_schema::container* c)
    : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
      Parameter_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
        this->parse (p, f);
      }
    }

    void Parameters::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // Parameter
        //
        if (n.name () == "Parameter" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< Parameter_type > r (
            Parameter_traits::create (i, f, this));

          this->Parameter_.push_back (::std::move (r));
          continue;
        }

        break;
      }
    }

    Parameters* Parameters::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class Parameters (*this, f, c);
    }

    Parameters& Parameters::
    operator= (const Parameters& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::type& > (*this) = x;
        this->Parameter_ = x.Parameter_;
      }

      return *this;
    }

    Parameters::
    ~Parameters ()
    {
    }

    // DefaultModel
    //

    DefaultModel::
    DefaultModel ()
    : ::xml_schema::string (),
      value_ (this)
    {
    }

    DefaultModel::
    DefaultModel (const char* _xsd_string_base)
    : ::xml_schema::string (_xsd_string_base),
      value_ (this)
    {
    }

    DefaultModel::
    DefaultModel (const ::std::string& _xsd_string_base)
    : ::xml_schema::string (_xsd_string_base),
      value_ (this)
    {
    }

    DefaultModel::
    DefaultModel (const ::xml_schema::string& _xsd_string_base)
    : ::xml_schema::string (_xsd_string_base),
      value_ (this)
    {
    }

    DefaultModel::
    DefaultModel (const DefaultModel& x,
                  ::xml_schema::flags f,
                  ::xml_schema::container* c)
    : ::xml_schema::string (x, f, c),
      value_ (x.value_, f, this)
    {
    }

    DefaultModel::
    DefaultModel (const ::xercesc::DOMElement& e,
                  ::xml_schema::flags f,
                  ::xml_schema::container* c)
    : ::xml_schema::string (e, f | ::xml_schema::flags::base, c),
      value_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
        this->parse (p, f);
      }
    }

    void DefaultModel::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::flags f)
    {
      while (p.more_attributes ())
      {
        const ::xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        if (n.name () == "value" && n.namespace_ ().empty ())
        {
          this->value_.set (value_traits::create (i, f, this));
          continue;
        }
      }
    }

    DefaultModel* DefaultModel::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class DefaultModel (*this, f, c);
    }

    DefaultModel& DefaultModel::
    operator= (const DefaultModel& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::string& > (*this) = x;
        this->value_ = x.value_;
      }

      return *this;
    }

    DefaultModel::
    ~DefaultModel ()
    {
    }

    // SpiceModel
    //

    SpiceModel::
    SpiceModel ()
    : ::xml_schema::string (),
      value_ (this)
    {
    }

    SpiceModel::
    SpiceModel (const char* _xsd_string_base)
    : ::xml_schema::string (_xsd_string_base),
      value_ (this)
    {
    }

    SpiceModel::
    SpiceModel (const ::std::string& _xsd_string_base)
    : ::xml_schema::string (_xsd_string_base),
      value_ (this)
    {
    }

    SpiceModel::
    SpiceModel (const ::xml_schema::string& _xsd_string_base)
    : ::xml_schema::string (_xsd_string_base),
      value_ (this)
    {
    }

    SpiceModel::
    SpiceModel (const SpiceModel& x,
                ::xml_schema::flags f,
                ::xml_schema::container* c)
    : ::xml_schema::string (x, f, c),
      value_ (x.value_, f, this)
    {
    }

    SpiceModel::
    SpiceModel (const ::xercesc::DOMElement& e,
                ::xml_schema::flags f,
                ::xml_schema::container* c)
    : ::xml_schema::string (e, f | ::xml_schema::flags::base, c),
      value_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
        this->parse (p, f);
      }
    }

    void SpiceModel::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::flags f)
    {
      while (p.more_attributes ())
      {
        const ::xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        if (n.name () == "value" && n.namespace_ ().empty ())
        {
          this->value_.set (value_traits::create (i, f, this));
          continue;
        }
      }
    }

    SpiceModel* SpiceModel::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class SpiceModel (*this, f, c);
    }

    SpiceModel& SpiceModel::
    operator= (const SpiceModel& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::string& > (*this) = x;
        this->value_ = x.value_;
      }

      return *this;
    }

    SpiceModel::
    ~SpiceModel ()
    {
    }

    // NgspiceNetlist
    //

    NgspiceNetlist::
    NgspiceNetlist ()
    : ::xml_schema::type (),
      Include_ (this),
      value_ (this)
    {
    }

    NgspiceNetlist::
    NgspiceNetlist (const NgspiceNetlist& x,
                    ::xml_schema::flags f,
                    ::xml_schema::container* c)
    : ::xml_schema::type (x, f, c),
      Include_ (x.Include_, f, this),
      value_ (x.value_, f, this)
    {
    }

    NgspiceNetlist::
    NgspiceNetlist (const ::xercesc::DOMElement& e,
                    ::xml_schema::flags f,
                    ::xml_schema::container* c)
    : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
      Include_ (this),
      value_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
        this->parse (p, f);
      }
    }

    void NgspiceNetlist::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // Include
        //
        if (n.name () == "Include" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< Include_type > r (
            Include_traits::create (i, f, this));

          if (!this->Include_)
          {
            this->Include_.set (::std::move (r));
            continue;
          }
        }

        break;
      }

      while (p.more_attributes ())
      {
        const ::xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        if (n.name () == "value" && n.namespace_ ().empty ())
        {
          this->value_.set (value_traits::create (i, f, this));
          continue;
        }
      }
    }

    NgspiceNetlist* NgspiceNetlist::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class NgspiceNetlist (*this, f, c);
    }

    NgspiceNetlist& NgspiceNetlist::
    operator= (const NgspiceNetlist& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::type& > (*this) = x;
        this->Include_ = x.Include_;
        this->value_ = x.value_;
      }

      return *this;
    }

    NgspiceNetlist::
    ~NgspiceNetlist ()
    {
    }

    // Symbol
    //

    Symbol::
    Symbol ()
    : ::xml_schema::type (),
      PortSym_ (this),
      Line_ (this),
      id_ (this)
    {
    }

    Symbol::
    Symbol (const Symbol& x,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
    : ::xml_schema::type (x, f, c),
      PortSym_ (x.PortSym_, f, this),
      Line_ (x.Line_, f, this),
      id_ (x.id_, f, this)
    {
    }

    Symbol::
    Symbol (const ::xercesc::DOMElement& e,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
    : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
      PortSym_ (this),
      Line_ (this),
      id_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
        this->parse (p, f);
      }
    }

    void Symbol::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // PortSym
        //
        if (n.name () == "PortSym" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< PortSym_type > r (
            PortSym_traits::create (i, f, this));

          this->PortSym_.push_back (::std::move (r));
          continue;
        }

        // Line
        //
        if (n.name () == "Line" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< Line_type > r (
            Line_traits::create (i, f, this));

          this->Line_.push_back (::std::move (r));
          continue;
        }

        break;
      }

      while (p.more_attributes ())
      {
        const ::xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        if (n.name () == "id" && n.namespace_ ().empty ())
        {
          this->id_.set (id_traits::create (i, f, this));
          continue;
        }
      }
    }

    Symbol* Symbol::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class Symbol (*this, f, c);
    }

    Symbol& Symbol::
    operator= (const Symbol& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::type& > (*this) = x;
        this->PortSym_ = x.PortSym_;
        this->Line_ = x.Line_;
        this->id_ = x.id_;
      }

      return *this;
    }

    Symbol::
    ~Symbol ()
    {
    }

    // Parameter
    //

    Parameter::
    Parameter (const Description_type& Description)
    : ::xml_schema::type (),
      Description_ (Description, this),
      name_ (this),
      unit_ (this),
      default_value_ (this),
      show_ (this)
    {
    }

    Parameter::
    Parameter (const Parameter& x,
               ::xml_schema::flags f,
               ::xml_schema::container* c)
    : ::xml_schema::type (x, f, c),
      Description_ (x.Description_, f, this),
      name_ (x.name_, f, this),
      unit_ (x.unit_, f, this),
      default_value_ (x.default_value_, f, this),
      show_ (x.show_, f, this)
    {
    }

    Parameter::
    Parameter (const ::xercesc::DOMElement& e,
               ::xml_schema::flags f,
               ::xml_schema::container* c)
    : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
      Description_ (this),
      name_ (this),
      unit_ (this),
      default_value_ (this),
      show_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
        this->parse (p, f);
      }
    }

    void Parameter::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::flags f)
    {
      for (; p.more_content (); p.next_content (false))
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // Description
        //
        if (n.name () == "Description" && n.namespace_ ().empty ())
        {
          ::std::unique_ptr< Description_type > r (
            Description_traits::create (i, f, this));

          if (!Description_.present ())
          {
            this->Description_.set (::std::move (r));
            continue;
          }
        }

        break;
      }

      if (!Description_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "Description",
          "");
      }

      while (p.more_attributes ())
      {
        const ::xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        if (n.name () == "name" && n.namespace_ ().empty ())
        {
          this->name_.set (name_traits::create (i, f, this));
          continue;
        }

        if (n.name () == "unit" && n.namespace_ ().empty ())
        {
          this->unit_.set (unit_traits::create (i, f, this));
          continue;
        }

        if (n.name () == "default_value" && n.namespace_ ().empty ())
        {
          this->default_value_.set (default_value_traits::create (i, f, this));
          continue;
        }

        if (n.name () == "show" && n.namespace_ ().empty ())
        {
          this->show_.set (show_traits::create (i, f, this));
          continue;
        }
      }
    }

    Parameter* Parameter::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class Parameter (*this, f, c);
    }

    Parameter& Parameter::
    operator= (const Parameter& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::type& > (*this) = x;
        this->Description_ = x.Description_;
        this->name_ = x.name_;
        this->unit_ = x.unit_;
        this->default_value_ = x.default_value_;
        this->show_ = x.show_;
      }

      return *this;
    }

    Parameter::
    ~Parameter ()
    {
    }

    // Include
    //

    Include::
    Include ()
    : ::xml_schema::string (),
      value_ (this)
    {
    }

    Include::
    Include (const char* _xsd_string_base)
    : ::xml_schema::string (_xsd_string_base),
      value_ (this)
    {
    }

    Include::
    Include (const ::std::string& _xsd_string_base)
    : ::xml_schema::string (_xsd_string_base),
      value_ (this)
    {
    }

    Include::
    Include (const ::xml_schema::string& _xsd_string_base)
    : ::xml_schema::string (_xsd_string_base),
      value_ (this)
    {
    }

    Include::
    Include (const Include& x,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
    : ::xml_schema::string (x, f, c),
      value_ (x.value_, f, this)
    {
    }

    Include::
    Include (const ::xercesc::DOMElement& e,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
    : ::xml_schema::string (e, f | ::xml_schema::flags::base, c),
      value_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
        this->parse (p, f);
      }
    }

    void Include::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::flags f)
    {
      while (p.more_attributes ())
      {
        const ::xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        if (n.name () == "value" && n.namespace_ ().empty ())
        {
          this->value_.set (value_traits::create (i, f, this));
          continue;
        }
      }
    }

    Include* Include::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class Include (*this, f, c);
    }

    Include& Include::
    operator= (const Include& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::string& > (*this) = x;
        this->value_ = x.value_;
      }

      return *this;
    }

    Include::
    ~Include ()
    {
    }

    // PortSym
    //

    PortSym::
    PortSym ()
    : ::xml_schema::string (),
      x_ (this),
      y_ (this),
      type_ (this),
      angle_ (this)
    {
    }

    PortSym::
    PortSym (const char* _xsd_string_base)
    : ::xml_schema::string (_xsd_string_base),
      x_ (this),
      y_ (this),
      type_ (this),
      angle_ (this)
    {
    }

    PortSym::
    PortSym (const ::std::string& _xsd_string_base)
    : ::xml_schema::string (_xsd_string_base),
      x_ (this),
      y_ (this),
      type_ (this),
      angle_ (this)
    {
    }

    PortSym::
    PortSym (const ::xml_schema::string& _xsd_string_base)
    : ::xml_schema::string (_xsd_string_base),
      x_ (this),
      y_ (this),
      type_ (this),
      angle_ (this)
    {
    }

    PortSym::
    PortSym (const PortSym& x,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
    : ::xml_schema::string (x, f, c),
      x_ (x.x_, f, this),
      y_ (x.y_, f, this),
      type_ (x.type_, f, this),
      angle_ (x.angle_, f, this)
    {
    }

    PortSym::
    PortSym (const ::xercesc::DOMElement& e,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
    : ::xml_schema::string (e, f | ::xml_schema::flags::base, c),
      x_ (this),
      y_ (this),
      type_ (this),
      angle_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
        this->parse (p, f);
      }
    }

    void PortSym::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::flags f)
    {
      while (p.more_attributes ())
      {
        const ::xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        if (n.name () == "x" && n.namespace_ ().empty ())
        {
          this->x_.set (x_traits::create (i, f, this));
          continue;
        }

        if (n.name () == "y" && n.namespace_ ().empty ())
        {
          this->y_.set (y_traits::create (i, f, this));
          continue;
        }

        if (n.name () == "type" && n.namespace_ ().empty ())
        {
          this->type_.set (type_traits::create (i, f, this));
          continue;
        }

        if (n.name () == "angle" && n.namespace_ ().empty ())
        {
          this->angle_.set (angle_traits::create (i, f, this));
          continue;
        }
      }
    }

    PortSym* PortSym::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class PortSym (*this, f, c);
    }

    PortSym& PortSym::
    operator= (const PortSym& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::string& > (*this) = x;
        this->x_ = x.x_;
        this->y_ = x.y_;
        this->type_ = x.type_;
        this->angle_ = x.angle_;
      }

      return *this;
    }

    PortSym::
    ~PortSym ()
    {
    }

    // Line
    //

    Line::
    Line ()
    : ::xml_schema::string (),
      x1_ (this),
      y1_ (this),
      x2_ (this),
      y2_ (this),
      color_ (this),
      width_ (this),
      style_ (this),
      x_ (this),
      y_ (this),
      type_ (this),
      angle_ (this)
    {
    }

    Line::
    Line (const char* _xsd_string_base)
    : ::xml_schema::string (_xsd_string_base),
      x1_ (this),
      y1_ (this),
      x2_ (this),
      y2_ (this),
      color_ (this),
      width_ (this),
      style_ (this),
      x_ (this),
      y_ (this),
      type_ (this),
      angle_ (this)
    {
    }

    Line::
    Line (const ::std::string& _xsd_string_base)
    : ::xml_schema::string (_xsd_string_base),
      x1_ (this),
      y1_ (this),
      x2_ (this),
      y2_ (this),
      color_ (this),
      width_ (this),
      style_ (this),
      x_ (this),
      y_ (this),
      type_ (this),
      angle_ (this)
    {
    }

    Line::
    Line (const ::xml_schema::string& _xsd_string_base)
    : ::xml_schema::string (_xsd_string_base),
      x1_ (this),
      y1_ (this),
      x2_ (this),
      y2_ (this),
      color_ (this),
      width_ (this),
      style_ (this),
      x_ (this),
      y_ (this),
      type_ (this),
      angle_ (this)
    {
    }

    Line::
    Line (const Line& x,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
    : ::xml_schema::string (x, f, c),
      x1_ (x.x1_, f, this),
      y1_ (x.y1_, f, this),
      x2_ (x.x2_, f, this),
      y2_ (x.y2_, f, this),
      color_ (x.color_, f, this),
      width_ (x.width_, f, this),
      style_ (x.style_, f, this),
      x_ (x.x_, f, this),
      y_ (x.y_, f, this),
      type_ (x.type_, f, this),
      angle_ (x.angle_, f, this)
    {
    }

    Line::
    Line (const ::xercesc::DOMElement& e,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
    : ::xml_schema::string (e, f | ::xml_schema::flags::base, c),
      x1_ (this),
      y1_ (this),
      x2_ (this),
      y2_ (this),
      color_ (this),
      width_ (this),
      style_ (this),
      x_ (this),
      y_ (this),
      type_ (this),
      angle_ (this)
    {
      if ((f & ::xml_schema::flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
        this->parse (p, f);
      }
    }

    void Line::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::flags f)
    {
      while (p.more_attributes ())
      {
        const ::xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        if (n.name () == "x1" && n.namespace_ ().empty ())
        {
          this->x1_.set (x1_traits::create (i, f, this));
          continue;
        }

        if (n.name () == "y1" && n.namespace_ ().empty ())
        {
          this->y1_.set (y1_traits::create (i, f, this));
          continue;
        }

        if (n.name () == "x2" && n.namespace_ ().empty ())
        {
          this->x2_.set (x2_traits::create (i, f, this));
          continue;
        }

        if (n.name () == "y2" && n.namespace_ ().empty ())
        {
          this->y2_.set (y2_traits::create (i, f, this));
          continue;
        }

        if (n.name () == "color" && n.namespace_ ().empty ())
        {
          this->color_.set (color_traits::create (i, f, this));
          continue;
        }

        if (n.name () == "width" && n.namespace_ ().empty ())
        {
          this->width_.set (width_traits::create (i, f, this));
          continue;
        }

        if (n.name () == "style" && n.namespace_ ().empty ())
        {
          this->style_.set (style_traits::create (i, f, this));
          continue;
        }

        if (n.name () == "x" && n.namespace_ ().empty ())
        {
          this->x_.set (x_traits::create (i, f, this));
          continue;
        }

        if (n.name () == "y" && n.namespace_ ().empty ())
        {
          this->y_.set (y_traits::create (i, f, this));
          continue;
        }

        if (n.name () == "type" && n.namespace_ ().empty ())
        {
          this->type_.set (type_traits::create (i, f, this));
          continue;
        }

        if (n.name () == "angle" && n.namespace_ ().empty ())
        {
          this->angle_.set (angle_traits::create (i, f, this));
          continue;
        }
      }
    }

    Line* Line::
    _clone (::xml_schema::flags f,
            ::xml_schema::container* c) const
    {
      return new class Line (*this, f, c);
    }

    Line& Line::
    operator= (const Line& x)
    {
      if (this != &x)
      {
        static_cast< ::xml_schema::string& > (*this) = x;
        this->x1_ = x.x1_;
        this->y1_ = x.y1_;
        this->x2_ = x.x2_;
        this->y2_ = x.y2_;
        this->color_ = x.color_;
        this->width_ = x.width_;
        this->style_ = x.style_;
        this->x_ = x.x_;
        this->y_ = x.y_;
        this->type_ = x.type_;
        this->angle_ = x.angle_;
      }

      return *this;
    }

    Line::
    ~Line ()
    {
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace component
{
  namespace xml
  {
    ::std::unique_ptr< ::component::xml::Component >
    Component_ (const ::std::string& u,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::flags::dont_initialize) == 0,
        (f & ::xml_schema::flags::keep_dom) == 0);

      ::xsd::cxx::tree::error_handler< char > h;

      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          u, h, p, f));

      h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

      return ::std::unique_ptr< ::component::xml::Component > (
        ::component::xml::Component_ (
          std::move (d), f | ::xml_schema::flags::own_dom, p));
    }

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (const ::std::string& u,
                ::xml_schema::error_handler& h,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::flags::dont_initialize) == 0,
        (f & ::xml_schema::flags::keep_dom) == 0);

      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          u, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      return ::std::unique_ptr< ::component::xml::Component > (
        ::component::xml::Component_ (
          std::move (d), f | ::xml_schema::flags::own_dom, p));
    }

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (const ::std::string& u,
                ::xercesc::DOMErrorHandler& h,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          u, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      return ::std::unique_ptr< ::component::xml::Component > (
        ::component::xml::Component_ (
          std::move (d), f | ::xml_schema::flags::own_dom, p));
    }

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::std::istream& is,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::flags::dont_initialize) == 0,
        (f & ::xml_schema::flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is);
      return ::component::xml::Component_ (isrc, f, p);
    }

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::std::istream& is,
                ::xml_schema::error_handler& h,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::flags::dont_initialize) == 0,
        (f & ::xml_schema::flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is);
      return ::component::xml::Component_ (isrc, h, f, p);
    }

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::std::istream& is,
                ::xercesc::DOMErrorHandler& h,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
    {
      ::xsd::cxx::xml::sax::std_input_source isrc (is);
      return ::component::xml::Component_ (isrc, h, f, p);
    }

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::std::istream& is,
                const ::std::string& sid,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::flags::dont_initialize) == 0,
        (f & ::xml_schema::flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
      return ::component::xml::Component_ (isrc, f, p);
    }

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::std::istream& is,
                const ::std::string& sid,
                ::xml_schema::error_handler& h,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::flags::dont_initialize) == 0,
        (f & ::xml_schema::flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
      return ::component::xml::Component_ (isrc, h, f, p);
    }

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::std::istream& is,
                const ::std::string& sid,
                ::xercesc::DOMErrorHandler& h,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
    {
      ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
      return ::component::xml::Component_ (isrc, h, f, p);
    }

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::xercesc::InputSource& i,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
    {
      ::xsd::cxx::tree::error_handler< char > h;

      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          i, h, p, f));

      h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

      return ::std::unique_ptr< ::component::xml::Component > (
        ::component::xml::Component_ (
          std::move (d), f | ::xml_schema::flags::own_dom, p));
    }

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::xercesc::InputSource& i,
                ::xml_schema::error_handler& h,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          i, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      return ::std::unique_ptr< ::component::xml::Component > (
        ::component::xml::Component_ (
          std::move (d), f | ::xml_schema::flags::own_dom, p));
    }

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::xercesc::InputSource& i,
                ::xercesc::DOMErrorHandler& h,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          i, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      return ::std::unique_ptr< ::component::xml::Component > (
        ::component::xml::Component_ (
          std::move (d), f | ::xml_schema::flags::own_dom, p));
    }

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (const ::xercesc::DOMDocument& doc,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
    {
      if (f & ::xml_schema::flags::keep_dom)
      {
        ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
          static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

        return ::std::unique_ptr< ::component::xml::Component > (
          ::component::xml::Component_ (
            std::move (d), f | ::xml_schema::flags::own_dom, p));
      }

      const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (e));

      if (n.name () == "Component" &&
          n.namespace_ () == "")
      {
        ::std::unique_ptr< ::component::xml::Component > r (
          ::xsd::cxx::tree::traits< ::component::xml::Component, char >::create (
            e, f, 0));
        return r;
      }

      throw ::xsd::cxx::tree::unexpected_element < char > (
        n.name (),
        n.namespace_ (),
        "Component",
        "");
    }

    ::std::unique_ptr< ::component::xml::Component >
    Component_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
                ::xml_schema::flags f,
                const ::xml_schema::properties&)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
        ((f & ::xml_schema::flags::keep_dom) &&
         !(f & ::xml_schema::flags::own_dom))
        ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
        : 0);

      ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
      const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (e));

      if (f & ::xml_schema::flags::keep_dom)
        doc.setUserData (::xml_schema::dom::tree_node_key,
                         (c.get () ? &c : &d),
                         0);

      if (n.name () == "Component" &&
          n.namespace_ () == "")
      {
        ::std::unique_ptr< ::component::xml::Component > r (
          ::xsd::cxx::tree::traits< ::component::xml::Component, char >::create (
            e, f, 0));
        return r;
      }

      throw ::xsd::cxx::tree::unexpected_element < char > (
        n.name (),
        n.namespace_ (),
        "Component",
        "");
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

