.TH Qucs-S "1" "June 2016" "Debian/GNU Linux" "User Commands"
.SH NAME
Qucs-S \- An universal GUI for SPICE and not-SPICE circuit simulators
.SH SYNOPSIS
.B qucs-s
[\fIOPTION\fR] ...
.SH DESCRIPTION

\fBQucs-S\fR is an unversal tool that provides GUI for different SPICE and 
not-SPICE circuit simulators. The following SPICE simulators are supported:
Ngspice, XYCE, and SpiceOpus. Also it allows to use not-SPICE simulation 
kernel Qucsator as simulation backends.

 
.SH AVAILABILITY
The latest version of Qucs-S can always be obtained from
\fBwww.sourceforge.net\fR or \fBwww.freshmeat.net\fR
.SH "REPORTING BUGS"
Known bugs are documented within the BUGS file.  Report bugs to
<qucs-bugs@lists.sourceforge.net>.
.SH COPYRIGHT
Copyright \(co 2015-2016 Vadim Kuznetsov <ra3xdh@gmail.com>, and Mike Brinson 
<mbrin72043@yahoo.co.uk>

Based on original Qucs code by M. Margraf, S. Jahn, G.B. Torri, et al.
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH AUTHORS
SPICE support written by 2015-2016 Vadim Kuznetsov <ra3xdh@gmail.com>, 
and Mike Brinson <mbrin72043@yahoo.co.uk>

Based on original Qucs code by M. Margraf, S. Jahn, G.B. Torri, et al.

